'use strict'

module.exports = {
  MAX_HEALTH: 100,
  MAX_LOADED_AMMO: 8,
  MAX_UNLOADED_AMMO: 24,

  NAME_MAX_LENGTH: 20,

  HEALTH_PACK_AMOUNT: 10,
  AMMO_PACK_AMOUNT: 8,

  INACTIVITY_LIMIT: [5, 'minutes'],
  DISCONNECTION_TIME_LIMIT: [1, 'minute'],
  NAME_CHANGE_FLOOD_LIMIT: [5, 'seconds']
}
